---
- name: Install k8s components
  hosts: all
  become: yes
  tasks:
    - name: Add k8s APT repository
      ansible.builtin.deb822_repository:
        name: kubernetes
        types: [deb]
        uris: "https://pkgs.k8s.io/core:/stable:/{{ k8s_version }}/deb/"
        signed_by: "https://pkgs.k8s.io/core:/stable:/{{ k8s_version }}/deb/Release.key"
        suites: [/]
        state: present
        enabled: yes

    - name: Install kublet, kubeadm and kubectl
      ansible.builtin.apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes
